### ISSUE TITLE
Checkout master branch

### ISSUE THREAD

**Issue by rahuldurrani** [rahuldurrani/ducktails#16]
Hello All!
I would like everyone to check out from the master branch and execute the code on their machines and test the project right now. If you spot any bugs or enhancements please log them in github issues and we can start working on it.

**Comment by terhuhf** [comment]
Can you write a brief README about how to run the program, including database, and etc..

**Comment by rahuldurrani** [comment]
I am working on it

**Comment by rahuldurrani** [comment]
I have updated the readme.

**Comment by terhuhf** [comment]
I noticed that "generic login page" is not merged into branch yet. Ill do another test after it's done!
