### ISSUE TITLE
New-created recipe not showing

### ISSUE THREAD

**Issue by terhuhf** [rahuldurrani/ducktails#26]
@rahuldurrani @anaparravera

**Comment by rahuldurrani** [comment]
Any details? Does it show up in the database?

**Comment by terhuhf** [comment]
After I create a new recipe, it prints out on terminal, but doesn't shows up on either homepage or "user profile" page.

**Comment by rahuldurrani** [comment]
That's strange, I have not been able to reproduce this issue.

**Comment by terhuhf** [comment]
That's fine. We just need it working on one machine to do presentation.

**Comment by rahuldurrani** [comment]
Can you pull from master now?
I have made a few changes

**Comment by terhuhf** [comment]
I pulled from master. When I test it, after I clicked "Post" button in the creation page, it jumped to home page immediately, while there was nothing new shown up. However, it printed out on my terminal.

Did you merge my commits in this morning? I solve issues that Ana posted yesterday.

**Comment by rahuldurrani** [comment]
I had merged a few changes last night so, i guess you might have been working on a previous commit.

**Comment by rahuldurrani** [comment]
I havent  merged your commits. Can you merge them into master ? I will pull from it

**Comment by terhuhf** [comment]
Ok, I'm gonna do it. Check out "interface.md" file in my commit, where I put data needed from backend.

**Comment by terhuhf** [comment]
I merged my changes into master.
