### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by anaparravera** [rahuldurrani/ducktails#4]
Before merging to template

**Comment by terhuhf** [comment]
#### Pages
* Homepage => Terence
* User profile => Terence
    + Recent activity
* Recipe detail => Terence
* Creation page => Daisy
* Search result page => Terence
#### Navigation Bar
* Navigation bar
* Search bar
* Login/signup, link to user profile
#### Document
* Data required from backend
* Path of each page
#### Different actions for other users and self
